from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional, Dict, Any, Set
from pathlib import Path
import hashlib, time, threading, json

# NEW: HTTP checks
import httpx

try:
    import yaml
except Exception:
    yaml = None

app = FastAPI(title="Mason Sidecar")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

# -------------------------
# STATE
# -------------------------
STATE: Dict[str, Any] = {
    "roots": [],
    "last_scan": None,
    "files": [],
    "proposals": [],
    "auto": False,
    "interval": 600,
    "auto_apply_safe": True,
}

BRIDGE: Dict[str, Any] = {
    "configured": False,
    "config_path": None,
    "cfg": {},
}

# NEW: Watchdog state
WATCH: Dict[str, Any] = {
    "services": [],     # list of dicts: {name,url,expect_code,interval_sec,next_due,last_status,last_error,last_time,consecutive_failures}
    "proposals": [],    # proposals generated by watchdog
}

# -------------------------
# UTIL & AUDIT
# -------------------------
def sha1_text(s: str) -> str:
    try:
        return hashlib.sha1(s.encode("utf-8","ignore")).hexdigest()
    except Exception:
        return hashlib.sha1(repr(s).encode("utf-8","ignore")).hexdigest()

def _audit_enabled() -> bool:
    try:
        return bool(BRIDGE.get("cfg",{}).get("audit",{}).get("log_file"))
    except Exception:
        return False

def _audit_path() -> Optional[Path]:
    p = BRIDGE.get("cfg",{}).get("audit",{}).get("log_file")
    return Path(p).resolve() if p else None

def audit_log(kind: str, data: Dict[str,Any]):
    if not _audit_enabled():
        return
    try:
        ap = _audit_path()
        ap.parent.mkdir(parents=True, exist_ok=True)
        with ap.open("a", encoding="utf-8") as f:
            f.write(json.dumps({"ts": time.time(), "kind": kind, "data": data}, ensure_ascii=False) + "\n")
    except Exception as e:
        print("audit_log error:", e)

# -------------------------
# FILE SCANNING & PROPOSALS
# -------------------------
def scan_root(root: Path):
    items = []
    for p in root.rglob("*"):
        if p.is_file() and not any(x in p.parts for x in [".venv","node_modules",".git",".parcel-cache",".expo","dist","__pycache__"]):
            try:
                txt = p.read_text(encoding="utf-8", errors="ignore")
            except Exception:
                txt = ""
            items.append({
                "path": str(p.relative_to(root)),
                "size": p.stat().st_size,
                "lines": txt.count("\n")+1 if txt else 0,
                "sha1": sha1_text(txt[:2000]) if txt else None,
                "snippet": txt[:400] if txt else "",
            })
    return items

def build_proposals(files: List[Dict[str,Any]]) -> List[Dict[str,Any]]:
    files_low = { f["path"].lower(): f for f in files }
    props: List[Dict[str,Any]] = []

    # 1) Inline TODOs → tasks
    todo_hits = [f for f in files if "todo" in (f.get("snippet") or "").lower()]
    if todo_hits:
        props.append({
            "id": sha1_text("todo-sweep"),
            "title": "Convert inline TODOs into backlog tasks",
            "impact": "medium",
            "apply": {"type":"instruction","text":"Extract TODOs into structured tasks in Onyx Tasks."},
            "evidence": [{"file": f["path"], "found":"TODO"} for f in todo_hits[:10]]
        })

    # 2) .env.local.example for onboarding
    if ".env.local" not in files_low and ".env.local.example" not in files_low:
        props.append({
            "id": sha1_text("env-example"),
            "title": "Add .env.local.example for easier setup",
            "impact": "low",
            "apply": {"type":"file_create","path":".env.local.example","content":"VITE_API_BASE=http://127.0.0.1:8000\n"},
            "evidence": []
        })

    # 3) .gitignore basics
    if ".gitignore" not in files_low:
        props.append({
            "id": sha1_text("gitignore"),
            "title": "Add a .gitignore for env & build artifacts",
            "impact": "low",
            "apply": {"type":"file_create","path":".gitignore","content":"# Onyx/Mason\n.venv/\n.env*\nnode_modules/\ndist/\n__pycache__/\n*.log\n"},
            "evidence": []
        })

    return props

def _merge_proposals(primary: List[Dict[str,Any]], extra: List[Dict[str,Any]]) -> List[Dict[str,Any]]:
    by_id = {p["id"]: dict(p) for p in primary}
    for e in extra:
        by_id[e["id"]] = dict(e)
    return list(by_id.values())

def do_scan(roots: List[str]):
    all_files = []
    for r in roots:
        root = Path(r)
        if root.exists():
            all_files.extend(scan_root(root))
    STATE["files"] = all_files
    STATE["last_scan"] = time.time()
    base_props = build_proposals(all_files)
    # Merge watchdog proposals so they’re always visible
    STATE["proposals"] = _merge_proposals(base_props, WATCH.get("proposals", []))
    audit_log("scan", {"roots": roots, "files": len(all_files), "proposals": len(STATE["proposals"])})
    return {"ok": True, "count": len(all_files), "proposals": len(STATE["proposals"])}

# -------------------------
# SAFE APPLY (no code edits)
# -------------------------
ALLOWED_APPLY_TYPES: Set[str] = {"file_create"}

def _safe_join(root: Path, rel: str) -> Path:
    p = (Path(root) / rel).resolve()
    if not str(p).startswith(str(Path(root).resolve())):
        raise ValueError("path escapes root")
    return p

def apply_safe_core(ids: Optional[List[str]]=None, target_root: Optional[str]=None) -> Dict[str,Any]:
    applied, skipped = [], []
    roots = [Path(target_root)] if target_root else [Path(r) for r in STATE["roots"]]
    # Prefer onyx-web root for top-level project files
    roots_sorted = sorted(roots, key=lambda p: 0 if "onyx-web" in str(p).lower() else 1)
    idset = set(ids) if ids else {p["id"] for p in STATE["proposals"]}

    for pr in STATE["proposals"]:
        if pr["id"] not in idset:
            continue
        ap = pr.get("apply") or {}
        if ap.get("type") not in ALLOWED_APPLY_TYPES:
            skipped.append({"id": pr["id"], "reason": "type_not_allowed"})
            continue

        rel = ap.get("path"); content = ap.get("content", "")
        if not rel or any(t in rel for t in ["..", ":", "\\..", "/.."]):
            skipped.append({"id": pr["id"], "reason": "bad_path"})
            continue

        last_err = None
        for root in roots_sorted:
            try:
                target = _safe_join(root, rel)
                target.parent.mkdir(parents=True, exist_ok=True)
                if target.exists():
                    skipped.append({"id": pr["id"], "reason": "exists", "path": str(target)})
                else:
                    target.write_text(content, encoding="utf-8")
                    applied.append({"id": pr["id"], "path": str(target)})
                break
            except Exception as e:
                last_err = str(e)
        else:
            skipped.append({"id": pr["id"], "reason": last_err or "no_root"})
    result = {"ok": True, "applied": applied, "skipped": skipped}
    audit_log("apply_safe", result)
    return result

# -------------------------
# WATCHDOG
# -------------------------
class WatchServiceBody(BaseModel):
    name: str
    url: str
    expect_code: int = 200
    interval_sec: int = 30

class WatchConfigBody(BaseModel):
    services: List[WatchServiceBody] = []

def _watch_tick():
    if not WATCH["services"]:
        return
    now = time.time()
    changed = False
    for svc in WATCH["services"]:
        due = float(svc.get("next_due", 0))
        if now < due:
            continue
        svc["next_due"] = now + int(svc.get("interval_sec", 30))
        code = None
        err = None
        try:
            with httpx.Client(timeout=5.0) as client:
                resp = client.get(svc["url"])
                code = resp.status_code
        except Exception as e:
            err = str(e)

        svc["last_time"] = now
        svc["last_status"] = code
        svc["last_error"] = err

        healthy = (code == int(svc.get("expect_code", 200)))
        pid = sha1_text(f"watch:{svc['name']}:{svc['url']}")
        if healthy:
            svc["consecutive_failures"] = 0
            # remove proposal if it exists
            WATCH["proposals"] = [p for p in WATCH["proposals"] if p["id"] != pid]
        else:
            svc["consecutive_failures"] = int(svc.get("consecutive_failures", 0)) + 1
            impact = "high" if svc["consecutive_failures"] >= 3 else "medium"
            title = f"Service '{svc['name']}' appears down"
            detail = f"Expected {svc.get('expect_code',200)}, got {code}. Failures: {svc['consecutive_failures']}."
            prop = {
                "id": pid,
                "title": title,
                "impact": impact,
                "apply": {"type":"instruction","text": f"Check {svc['name']} at {svc['url']}. {detail}"},
                "evidence": [{"last_status": code, "last_error": err, "time": now}],
            }
            # upsert
            for i, p in enumerate(WATCH["proposals"]):
                if p["id"] == pid:
                    WATCH["proposals"][i] = prop
                    break
            else:
                WATCH["proposals"].append(prop)
        changed = True
        audit_log("watch_check", {"name": svc["name"], "url": svc["url"], "status": code, "error": err})

    if changed:
        # merge into STATE without losing existing file-based proposals
        STATE["proposals"] = _merge_proposals(STATE.get("proposals", []), WATCH.get("proposals", []))

# -------------------------
# MODELS
# -------------------------
class StartBody(BaseModel):
    roots: List[str]
    interval_sec: Optional[int] = 600

class ScanBody(BaseModel):
    roots: List[str]

class BridgeConfigBody(BaseModel):
    path: str

class ApplyBody(BaseModel):
    ids: Optional[List[str]] = None
    target_root: Optional[str] = None

class AutoConfigBody(BaseModel):
    auto_apply_safe: Optional[bool] = None
    interval_sec: Optional[int] = None

# -------------------------
# ROUTES
# -------------------------
@app.get("/health")
def health():
    return {"ok": True, "auto": STATE["auto"], "last_scan": STATE["last_scan"], "auto_apply_safe": STATE["auto_apply_safe"]}

@app.post("/auto/start")
def auto_start(b: StartBody):
    STATE["roots"] = [str(Path(r).resolve()) for r in b.roots]
    STATE["interval"] = int(b.interval_sec or 600)
    STATE["auto"] = True
    threading.Thread(target=auto_loop, daemon=True).start()
    return {"ok": True, "watching": STATE["roots"]}

@app.post("/auto/stop")
def auto_stop():
    STATE["auto"] = False
    return {"ok": True}

@app.post("/auto/config")
def auto_config(b: AutoConfigBody):
    if b.auto_apply_safe is not None:
        STATE["auto_apply_safe"] = bool(b.auto_apply_safe)
    if b.interval_sec is not None:
        STATE["interval"] = int(b.interval_sec)
    return {"ok": True, "auto_apply_safe": STATE["auto_apply_safe"], "interval_sec": STATE["interval"]}

@app.post("/scan")
def scan_now(b: ScanBody):
    return do_scan(b.roots)

@app.get("/proposals")
def proposals():
    return {"ok": True, "count": len(STATE["proposals"]), "items": STATE["proposals"]}

@app.post("/apply/safe")
def apply_safe(b: ApplyBody):
    return apply_safe_core(ids=b.ids, target_root=b.target_root)

@app.get("/audit/tail")
def audit_tail(lines: int = 50):
    if not _audit_enabled():
        return {"ok": False, "error": "audit not configured"}
    ap = _audit_path()
    if not ap.exists():
        return {"ok": True, "lines": []}
    try:
        with ap.open("r", encoding="utf-8") as f:
            buff = f.readlines()[-max(1, min(500, int(lines))):]
        return {"ok": True, "lines": buff}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/bridge/status")
def bridge_status():
    return {
        "ok": True,
        "configured": BRIDGE["configured"],
        "assistant": (BRIDGE["cfg"].get("assistant") if BRIDGE["cfg"] else None),
        "forbidden": (BRIDGE["cfg"].get("guardrails",{}).get("forbidden",[]) if BRIDGE["cfg"] else []),
        "review": (BRIDGE["cfg"].get("review",{}) if BRIDGE["cfg"] else {}),
        "audit_file": (BRIDGE["cfg"].get("audit",{}).get("log_file") if BRIDGE["cfg"] else None),
    }

@app.post("/bridge/config")
def bridge_config(b: BridgeConfigBody):
    cfg_path = Path(b.path).expanduser().resolve()
    if not cfg_path.exists():
        return {"ok": False, "error": f"config not found: {cfg_path}"}
    if yaml is None:
        return {"ok": False, "error": "pyyaml not installed"}
    data = yaml.safe_load(cfg_path.read_text(encoding="utf-8"))
    BRIDGE["configured"] = True
    BRIDGE["config_path"] = str(cfg_path)
    BRIDGE["cfg"] = data or {}
    audit_log("bridge_configured", {"path": str(cfg_path)})
    return {"ok": True, "path": str(cfg_path)}

# NEW: Watchdog routes
@app.post("/watch/config")
def watch_config(b: WatchConfigBody):
    WATCH["services"] = []
    for s in b.services:
        WATCH["services"].append({
            "name": s.name,
            "url": s.url,
            "expect_code": int(s.expect_code),
            "interval_sec": int(s.interval_sec),
            "next_due": 0.0,
            "last_status": None,
            "last_error": None,
            "last_time": None,
            "consecutive_failures": 0,
        })
    WATCH["proposals"] = []
    audit_log("watch_config", {"count": len(WATCH["services"])})
    return {"ok": True, "count": len(WATCH["services"])}

@app.get("/watch/status")
def watch_status():
    return {
        "ok": True,
        "services": WATCH["services"],
        "proposals": len(WATCH.get("proposals", [])),
    }

# -------------------------
# AUTO LOOP
# -------------------------
def auto_loop():
    while STATE["auto"]:
        try:
            # Main scan cycle
            if STATE["roots"]:
                do_scan(STATE["roots"])
                if STATE.get("auto_apply_safe"):
                    apply_safe_core(ids=None, target_root=None)

            # Per-second ticks until next scan
            for _ in range(STATE.get("interval",600)):
                if not STATE["auto"]:
                    break
                _watch_tick()        # run watchdog checks
                time.sleep(1)
        except Exception as e:
            print("auto_loop error:", e)

# -------------------------
# MAIN
# -------------------------
if __name__ == "__main__":
    import uvicorn
    uvicorn.run("sidecar:app", host="127.0.0.1", port=7000, reload=False)
